### ISSUE TITLE
Just show warning when run command

### ISSUE THREAD

**Issue by kyoz** [segeljakt/vim-silicon#1]
By default, vim-silicon will show warning about silicon isn't installed when vim started up.

I think it's better than just show message about install silicon is required when perform vim-silicon commands. Because sometimes we can't install silicon in some os...

**Comment by segeljakt** [comment]
Good point, I'll fix it

**Comment by segeljakt** [comment]
Sorry about the wait, this should be solved now. If not, please reopen the issue.
