### ISSUE TITLE
neovim compatibility

### ISSUE THREAD

**Issue by al-jshen** [segeljakt/vim-silicon#12]
Is this compatible with neovim? I'm getting 

`"Undefined variable: g:silicon"`

on the line

`let g:silicon['output'] = '/output/directory'`

Thanks.

**Comment by abecodes** [comment]
@al-jshen you need to set `silicon` first.
Smth like `let g:silicon={}`

**Comment by al-jshen** [comment]
Thanks! A little strange, I'd expect the default configuration to kick in without having to do that.
