### ISSUE TITLE
"only supported on Linux" error on Linux

### ISSUE THREAD

**Issue by Noah2610** [segeljakt/vim-silicon#2]
I am on Linux (Arch) with `xclip` installed.
When I use `:Silicon` without specifying a path, I get the error that copying to clipboard is only supported on Linux.
![silicon-error](https://user-images.githubusercontent.com/22497730/62372060-c2a58680-b536-11e9-95ae-8d813a380206.png)
<sup>_yes, I used silicon for this image :)_</sup>

This has to do with this line https://github.com/segeljakt/vim-silicon/blob/master/autoload/silicon.vim#L91
Running `has('linux')` returns false (I do not know vimscript).

I am happy to provide any additional info you might need about my system.

**Comment by segeljakt** [comment]
Thanks for the report, I thought `has('linux')` would return true for all distributions of Linux but it appears not. I replaced `has('linux')` with `executable('xclip')`, so hopefully it will work now :)

If you experience any problems or performance degradation please reopen the issue and let me know.

**Comment by Noah2610** [comment]
Works without problems now, thanks!
